package fr.utbm.formation.core.entity;
// Generated 26 nov. 2016 11:34:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CourseSession generated by hbm2java
 */
public class CourseSession  implements java.io.Serializable {


     private int idSession;
     private Date startDate;
     private Date endDate;
     private Course course;
     private Location location;

    public Course getCourse() {
        return course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }

    public CourseSession() {
    }

	
    public CourseSession(int idSession, Date startDate, Date endDate) {
        this.idSession = idSession;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public CourseSession(int idSession, Date startDate, Date endDate, String courseCode, Integer locationId) {
       this.idSession = idSession;
       this.startDate = startDate;
       this.endDate = endDate;
       this.course = course;
       this.location = location;
    }
   
    public int getIdSession() {
        return this.idSession;
    }
    
    public void setIdSession(int idSession) {
        this.idSession = idSession;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
   




}


