package fr.utbm.formation.core.entity;
// Generated Oct 22, 2016 11:35:14 AM by Hibernate Tools 4.3.1



/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private String city;

    public Location() {
    }

    public Location(int id, String city) {
       this.id = id;
       this.city = city;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


