package fr.utbm.formation.entity;
// Generated Oct 22, 2016 11:35:14 AM by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int idClient;
     private String lastname;
     private String firstname;
     private String address;
     private long phone;
     private String email;
     private Integer courseSessionId;

    public Client() {
    }

	
    public Client(int idClient, String lastname, String firstname, String address, long phone, String email) {
        this.idClient = idClient;
        this.lastname = lastname;
        this.firstname = firstname;
        this.address = address;
        this.phone = phone;
        this.email = email;
    }
    public Client(int idClient, String lastname, String firstname, String address, long phone, String email, Integer courseSessionId) {
       this.idClient = idClient;
       this.lastname = lastname;
       this.firstname = firstname;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.courseSessionId = courseSessionId;
    }
   
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public long getPhone() {
        return this.phone;
    }
    
    public void setPhone(long phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getCourseSessionId() {
        return this.courseSessionId;
    }
    
    public void setCourseSessionId(Integer courseSessionId) {
        this.courseSessionId = courseSessionId;
    }




}


