package fr.utbm.formation.entity;
// Generated Oct 22, 2016 11:35:14 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CourseSession generated by hbm2java
 */
public class CourseSession  implements java.io.Serializable {


     private int idSession;
     private Date startDate;
     private Date endDate;
     private String courseCode;
     private Integer locationId;

    public CourseSession() {
    }

	
    public CourseSession(int idSession, Date startDate, Date endDate) {
        this.idSession = idSession;
        this.startDate = startDate;
        this.endDate = endDate;
    }
    public CourseSession(int idSession, Date startDate, Date endDate, String courseCode, Integer locationId) {
       this.idSession = idSession;
       this.startDate = startDate;
       this.endDate = endDate;
       this.courseCode = courseCode;
       this.locationId = locationId;
    }
   
    public int getIdSession() {
        return this.idSession;
    }
    
    public void setIdSession(int idSession) {
        this.idSession = idSession;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }




}


